install.packages("tidyverse")
library(ggplot2)
library(tidyverse)
dat <- read.csv("scales.csv")
dim(dat)
head(dat)
class(dat$N)
class(dat$quadrant)
class(dat$species)
class(dat$specimen)
class(dat[,1])
class(dat[,2])
class(dat[,3])
class(dat[,4])
mean(dat$N)
sapply(dat,class)
